# Generated by Django 5.2 on 2025-04-11 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_favoritecity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeatherData',
        ),
    ]
